# Generated by Django 5.1.2 on 2024-11-07 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_plans', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyplan',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('completed', 'Completed')], default='draft', max_length=10),
        ),
    ]
