# Generated by Django 5.1.2 on 2024-12-17 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_period'),
        ('study_plans', '0003_alter_studyplancourse_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studyplancourse',
            unique_together={('study_plan', 'course')},
        ),
        migrations.RemoveField(
            model_name='studyplancourse',
            name='is_completed',
        ),
        migrations.RemoveField(
            model_name='studyplancourse',
            name='semester',
        ),
    ]
