CREATE SCHEMA IF NOT EXISTS dev;

GRANT ALL PRIVILEGES ON SCHEMA dev TO postgres;

ALTER DEFAULT PRIVILEGES IN SCHEMA dev GRANT ALL PRIVILEGES ON TABLES TO postgres;

ALTER DEFAULT PRIVILEGES IN SCHEMA dev GRANT ALL PRIVILEGES ON SEQUENCES TO postgres;