# Generated by Django 5.1.2 on 2024-11-07 00:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('programmes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgrammeCourse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year', models.IntegerField()),
                ('period_months', models.IntegerField()),
                ('is_mandatory', models.BooleanField(default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programmes.programme')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
