# Generated by Django 5.1.2 on 2024-11-07 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_learning_outcomes_course_prerequisites'),
        ('programmes', '0002_programmecourse'),
    ]

    operations = [
        migrations.AddField(
            model_name='programme',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='programmes', through='programmes.ProgrammeCourse', to='courses.course'),
        ),
    ]
