# Generated by Django 5.1.2 on 2024-11-05 23:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('courseName', models.CharField(max_length=255)),
                ('courseCode', models.CharField(max_length=255)),
                ('credits', models.DecimalField(decimal_places=2, max_digits=5)),
                ('educationalLevel', models.CharField(max_length=255)),
                ('courseDescription', models.TextField()),
                ('mainArea', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
