# Generated by Django 5.1.2 on 2024-11-24 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_learning_outcomes_course_prerequisites'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='semester',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
