# Generated by Django 5.1.2 on 2024-12-17 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='period',
            field=models.PositiveIntegerField(choices=[(1, 'First Period'), (2, 'Second Period'), (3, 'Both Periods')], default=3),
        ),
    ]
