version: "3.8"
services:
  test_web:
    build:
      context: ..
      dockerfile: docker/Dockerfile1
    restart: always
    ports:
      - "8080:8000"
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ../:/app
    depends_on:
      test_db:
        condition: service_healthy
    environment:
      - ENVIRONMENT=test
      - SECRET_KEY=secret
      - DB_NAME=test_db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=test_db

  test_db:
    image: postgres:latest
    environment:
      - ENVIRONMENT=test
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=test_db
    ports:
      - "5432:5432"
    volumes:
      - test_db_data:/var/lib/postgresql/data/
      - ./init-db:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  test_db_data:
