version: "3"
services:
  web:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    restart: always
    ports:
      - "8000:8000"
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ../:/app
    depends_on:
      db:
        condition: service_healthy
    environment:
      - ENVIRONMENT=development
      - SECRET_KEY=secret
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=db


  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./init-db:/docker-entrypoint-initdb.d
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 2s
      retries: 5

volumes:
  postgres_data:
