version: "3.7"
services:
  web:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    restart: always
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ../:/app
    env_file:
      - ../.env

  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - "80:80"
    volumes:
      - ../:/app
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web


