name: Tests ⚙️

on:
  pull_request:
    branches:
      - dev
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run tests
      run: |
        chmod +x ./run_tests.sh
        ./run_tests.sh
